#define ONEWIRE_BUS_GPIO 4
#define ONEWIRE_MAX_DS18B20 10
#define ONEWIRE_SEARCH_RETRY_DELAY_MS 2000
#define ONEWIRE_SEARCH_RETRY_COUNT 10
#define WIFI_MAXIMUM_RETRY 20
#define MAX_HTTP_OUTPUT_BUFFER 512
